name: Deploy AWS Lambda Now

on: # defines when our workflow is gonna run
  push: #triggers our workflow on push events
    branches:
      - main
    paths: 
      - 'lambda/**'

jobs:
  deploy-lambda:  #name of our job
    runs-on: ubuntu-latest    #sets or specifies the runner
    steps:
    - uses: actions/checkout@v2

    - name: Set Up Python   #sets up our python env
      uses: actions/setup-python@v2
      with: 
        python-version: '3.12'

    - name: Install Dependencies    #Installs any packages
      run: |
          python -m pip install --upgrade pip
          pip install -r lambda/requirements.txt -t lambda/

    - name: Configure AWS Creds   #Sets up our AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Deploy Lambda Function     #zips lambda directory and updates lambda function
      run: |
        cd lambda
        zip -r lambda.zip .
        aws lambda update-function-code --function-name Test-Lambda --zip-file fileb://lambda.zip

